name: Run trading script

on:
  workflow_dispatch:   # manuell testkörning
  schedule:
    - cron: "0 6 * * *"  # varje dag 06:00 UTC (valfritt)

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pwd
      
      - run: ls -la
      
      - run: find . -maxdepth 2 -type f

      - name: Install dependencies
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt

      - run: python traiding.py